# Generated by Django 3.0.4 on 2020-03-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200311_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_view_instance', 'Can view book instance'),)},
        ),
    ]
