# Generated by Django 3.0.4 on 2020-03-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200311_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_view_instance', 'Librarienii pot vedea cine a luat cartile'),)},
        ),
    ]
